# Generated by Django 3.2.6 on 2021-08-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nfl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='app_nfl.team'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='app_nfl.team'),
        ),
    ]
